### ISSUE TITLE
Custom flow file for customer roadnet file

### ISSUE THREAD

**Issue by mainakchain** [cityflow-project/data#3]
I have generated the roadnet file from the sumo net.xml file. But how to get the corresponding flow file? In other words, how to generate the file corresponding to _atlanta_flow.json_?

 @zhc134 @soodoshll @only-changer

**Comment by only-changer** [comment]
Regrettably, there is no auto flow generator for now. I suggest that you can manually select some possible start point and endpoint, then write a script to format them to flow.json. Note that you do not need to specify the route from the start point to the endpoint, since Cityflow has an auto route generator.

Sorry for the inconvenience.
